### ISSUE TITLE
unhelpfull error message when php curl not installed

### ISSUE THREAD

**Issue by renepickhardt** [ElementsProject/woocommerce-gateway-lightning#10]
When `php-curl` ist not installed proceeding to payment yields the following error message:

   Internal Server Error

The apache error log referes to php-restclient/restclient.php line 135. This call to curl should be wrapped into try catch and yield a helpfull error message.  However I cannot find the referenced file in the git repo (so I could not look into the source code)

`[Fri Jan 26 00:15:53.203187 2018] [:error] [pid 3167] [client ::1:36028] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/wordpress/wp-content/plugins/woocommerce-gateway-lightning/vendor/tcdent/php-restclient/restclient.php:135\nStack trace:\n#0 /var/www/html/wordpress/wp-content/plugins/woocommerce-gateway-lightning/vendor/tcdent/php-restclient/restclient.php(113): RestClient->execute('/invoice', 'POST', '{"currency":"BT...', Array)\n#1 /var/www/html/wordpress/wp-content/plugins/woocommerce-gateway-lightning/vendor/elementsproject/lightning-charge-client-php/client.php(22): RestClient->post('/invoice', '{"currency":"BT...', Array)\n#2 /var/www/html/wordpress/wp-content/plugins/woocommerce-gateway-lightning/woocommerce-gateway-lightning.php(114): LightningChargeClient->invoice(Array)\n#3 /var/www/html/wordpress/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(804): WC_Gateway_Lightning->process_payment(10)\n#4 /var/www/html/wordpress/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(986): WC_Checkout->process_order_payment(10, 'lightning' in /var/www/html/wordpress/wp-content/plugins/woocommerce-gateway-lightning/vendor/tcdent/php-restclient/restclient.php on line 135, referer: http://localhost/wordpress/index.php/checkout/`

This is particular important for the people who are running on managed hosting and have no access to error logs and can't know if php curl is installed.

**Comment by shesek** [comment]
Thanks for the suggestion, added in https://github.com/ElementsProject/woocommerce-gateway-lightning/commit/ca40a13ed1289d95c0bd4d8305fdcd9ccc041b90.

The error will look like that:

![image](https://user-images.githubusercontent.com/877904/35421079-d1a798c2-0249-11e8-8c3c-c87e87ef5ee3.png)

**Comment by renepickhardt** [comment]
thanks for the fix. I tried to extend this a little bit for inexperienced users (which are most likely to run into this problem if they are not self hosting their site)
