### ISSUE TITLE
Error in doing lighting charge payment

### ISSUE THREAD

**Issue by Dhara-Openxcell** [ElementsProject/woocommerce-gateway-lightning#12]
I am getting following error while doing payment for generated invoice by lightning charge api.
**"This is not a valid bitcoin address".**
We are doing payment using this app : **Eclair Wallet Testnet**
[https://play.google.com/store/apps/details?id=fr.acinq.eclair.wallet&hl=en
](https://play.google.com/store/apps/details?id=fr.acinq.eclair.wallet&hl=en
)
Also here we have attached generated invoice address by plugin.

![screenshot from 2018-02-13 18-58-09](https://user-images.githubusercontent.com/35023605/36152128-dbedf330-10ef-11e8-88ae-a61a1dd5f012.png)

Can you help us to figure out what we are doing wrong ? Also we have set up c - lightning and lightning charge on our local server. 

Thanks.

**Comment by shesek** [comment]
Cause identified by https://github.com/ElementsProject/lightning/issues/984#issuecomment-365632398, closing.

**Comment by shesek** [comment]
It appears like Eclair now supports QRs with the `lightning:` prefix.
