### ISSUE TITLE
Is there a way to also store the bitcoin amount in the order metadata?

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/woocommerce-gateway-lightning#13]
Just wondering whether that is a thing that could be added, since the conversion from dollar amounts to Bitcoin depends on the order time, it'd be great to have this added to the metadata. Does woocommerce allow this kind of associated data storage?

**Comment by shesek** [comment]
WooCommerce does allow associating metadata with orders, and this is [already used](https://github.com/ElementsProject/woocommerce-gateway-lightning/blob/fbcd540753a6cdfce5f24fd6b88bf89dbc6cb9eb/woocommerce-gateway-lightning.php#L209-L211) to keep the full invoice JSON object from Charge alongside the order, under a key named `_lightning_invoice`.

The msatoshi amount is accessible programmatically via `wc_get_order($order_id)->get_meta('_lightning_invoice')->msatoshi`.

The lightning invoice is also [available when exporting](https://user-images.githubusercontent.com/877904/42548963-742e0a8a-84d2-11e8-9d32-3a2be7758102.png) orders (note that you'll get the entire JSON string as a single CSV column).

However, it appears like WooCommerce doesn't display metadata fields in the orders admin dashboard out-of-the-box, but does have [a paid plugin](https://woocommerce.com/products/admin-custom-order-fields/) to do so.

The WooCommerce Gateway Plugin could be modified to display that somewhere in the order screen itself, maybe as part of the [note that gets added](https://user-images.githubusercontent.com/877904/42548911-24ced460-84d2-11e8-894b-322094b68f9d.png), or in some more specialized area?

**Comment by cdecker** [comment]
The main goal is to get those values into the advanced order export reports. So I'll take a look at that instead.

**Comment by cdecker** [comment]
Ok, found a way to do it, however the value is inside a serialized PHP class, maybe we could extract that to be a standalone int as metadata field?

**Comment by shesek** [comment]
Added the invoice `id`, `rhash`, `msatoshi` and `msatoshi_received` as direct metadata fields in 22a68e3bd8c037754d67358fe5cf7832f2cad280. This results in some data duplication, but makes the fields much easier to access in WooCommerce's dashboard. Released in [`v0.2.4`](https://github.com/ElementsProject/woocommerce-gateway-lightning/releases/tag/v0.2.4).

This is how it looks when viewing an order:

![image](https://user-images.githubusercontent.com/877904/42724162-db9d8330-8775-11e8-8ff3-76cba5ba0286.png)
