### ISSUE TITLE
Is this thing working?

### ISSUE THREAD

**Issue by JaviLib** [ElementsProject/woocommerce-gateway-lightning#17]
Is this thing working?
Latelly with new versions of Woo,  I'm unable to receive payments. It says "failed saving invoice".

**Comment by shesek** [comment]
Did this previously work for you? Which version of WooCommerce did you upgrade to and which did you use before? Are you certain your Lightning Charge server is running?

**Comment by JaviLib** [comment]
It is working for now, thank you.
