### ISSUE TITLE
Failed saving invoice

### ISSUE THREAD

**Issue by otaviobonder** [ElementsProject/woocommerce-gateway-lightning#9]
`Lightningd` is running and `Charged` is running as well. `Charged` shows `HTTP server running on localhost:9112`. My router port is open, and the lightning charge server on the plugin settings page points to my ip:9112.

However, when I try to create a payment using LN, Woocommerce shows `failed saving invoice`

**Comment by shesek** [comment]
1. Do you have the Lightning Charge API token configured in WooCommerce's settings?

2. Are WordPress and Lightning Charge running on the same server?

3. If not, are you able to access Lightning Charge using `curl` from the machine running WordPress? You can try something like:

       $ curl -u api-token:[your-token] http://[ln.charge.hostname]:9112/invoices

**Comment by otaviobonder** [comment]
1. Yes, API token configured
2. No, WordPress running on SiteGround
3. No, I get a connection failed even if my router port is correctly redirected to charged server

**Comment by shesek** [comment]
Try running charged with `--host 0.0.0.0`

**Comment by otaviobonder** [comment]
No job, connection timed out.

**Comment by shesek** [comment]
Are you able to access charged locally? Try this from the machine running charged:

    $ curl -u api-token:[your-token] http://127.0.0.1:9112/invoices

If this works, I'm not really sure how to help you... this appears to be a router configuration issue.

**Comment by otaviobonder** [comment]
Yes I can, already tested it. Could create an invoice either

**Comment by otaviobonder** [comment]
I've already checked if the router port is really open using `https://www.yougetsignal.com/tools/open-ports/` and it's everything fine with this port.

**Comment by shesek** [comment]
Can you access the server by typing your public IP address into your browser URL bar?

**Comment by otaviobonder** [comment]
Yes, I can connect to it using SSH

**Comment by shesek** [comment]
SSH is different. Are you able to access the HTTP server running on port 9112?

**Comment by otaviobonder** [comment]
Yes, typing my `IP address:9112` I receive `Cannot GET /`

**Comment by shesek** [comment]
Oh, interesting. Then its probably not an issue with your router, but rather on SiteGround's side. My guess is that they're blocking outgoing requests to non-standard ports.

Can you set your router to forward port 80 to your machine's port 9112?

**Comment by otaviobonder** [comment]
Now I can't connect using my browser either

**Comment by shesek** [comment]
Looks like port 80 might already be used for something else. Hmm, maybe reach out to SiteGround and ask them to whitelist port 9112, or give you the list of whitelisted ports and try to use one of them?

**Comment by otaviobonder** [comment]
Thank you again mate, will do it. Port 80 is used for Web Management, so I will try to change it to another port. If I get no success, I will contact them!

**Comment by shesek** [comment]
Other ports that are commonly open include 443 (typically used for SSL, but you could use it for HTTP), 8080 and 81.

**Comment by shesek** [comment]
443 being the most common of them all, I would try that first if your router isn't listening on it already.

**Comment by shesek** [comment]
I'm closing this issue because its not charge-related, but feel free to continue posting here if you have more questions.

**Comment by otaviobonder** [comment]
You were right sir! SiteGround was blocking the port. Now everything is working fine! Just one offtopic question, it seems that the invoice number isn't line breaking, I'm sending the image attached. Do you know how to configure it?
![lnpayment](https://user-images.githubusercontent.com/28715087/35351517-4227af6a-0128-11e8-9328-f2af4b050bd4.PNG)

**Comment by shesek** [comment]
Add `.ln-pay .payreq { word-wrap: break-word; }` to your CSS. 

Note that this isn't the invoice number, its the [BOLT11](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md) payment request.

**Comment by otaviobonder** [comment]
Yes sure, BOLT11, sorry for the mistake and thank you for the css code, sir!

**Comment by vnnkl** [comment]
for anyone who might experience the similar issue with no line break after paying the invoice,
the css code for that is
`.woocommerce-order .order_details{ word-wrap: break-word; }`

**Comment by shesek** [comment]
@vnnkl Added in https://github.com/ElementsProject/woocommerce-gateway-lightning/commit/7da4990dfcbb1906906e23c1cf007a376b6a7ae0.

**Comment by cmatrade** [comment]
Hi, 
I have the same issue with the error msg "failed saving invoice", what the port did you configure into your router ? thanks

**Comment by normandmickey** [comment]
I have the same "failed saving invoice" problem.  My WordPress/Woocommerce site is hosted at Pressable.  My lightning node is self hosted and Lightning Charge works with NanoPos.  The port is open and I get a response when I "curl $CHARGE/info" using the API token from a separate machine.  Upgraded to latest Lightning Charge, still no joy.

**Comment by shesek** [comment]
@normandmickey Some suggestions:

1. > The port is open and I get a response when I "curl $CHARGE/info" using the API token from a separate machine.

    Can you verify this works if you run this from the same machine running WordPress?

2. Are there any logs generated on Lightning Charge when you attempt to make an order on WooCommerce? If the request for creating the invoice is coming through, you should be seeing something there.

3. Are you able to create an invoice with `curl $CHARGE/invoice -d msatoshi=500`?

**Comment by normandmickey** [comment]
1.  I dont have command line access to the WordPress site.  Its hosted at
Pressable.  I will try to install WP on the lightning nodes machine soon to
test locally.

2.  I dont see any activity on the Lightning node when trying to create an
invoice with the plugin.

3.  Yes from another remote and locally on the Lightning node.

**Comment by shesek** [comment]
It appears to be some communication problem between the two servers. Maybe Pressable is rejecting the outgoing connection?

Are you using the default port (9112) for Charge? Some firewalls don't like non-standard ports, which might be a reason Pressable blocks it. You might have better look running on port 80.
